name: bot
version: 0.16.3-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
documentation: http://kevmoo.github.com/bot.dart
environment:
  sdk: '>=0.4.5+1.r21094'
dependencies:
  unittest: '>=0.4.5+1'
  args: '>=0.4.5+1'
  logging: '>=0.4.5+1'
  pathos: '>=0.4.5+1'
  meta: '>=0.4.5+1'
dev_dependencies:
  html5lib: '>=0.4.1'
  browser: '>=0.4.5+1'
