name: git
version: 0.4.5-dev
author: Kevin Moore <github@j832.com>
description: A Dart wrapper around the Git command line
homepage: https://github.com/kevmoo/git.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  path: ^1.0.0
dev_dependencies:
  test: ^0.12.0
  test_descriptor: ^1.0.3
