name: git
version: 0.4.5-dev
author: Kevin Moore <github@j832.com>
description: A Dart wrapper around the Git command line
homepage: https://github.com/kevmoo/git.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.29.0'
  which: ^0.1.3
  path: ^1.0.0
dev_dependencies:
  scheduled_test: ^0.12.0
  test: ^0.12.0
