name: git
version: 0.5.2-dev
author: Kevin Moore <github@j832.com>
description: A Dart wrapper around the Git command line
homepage: https://github.com/kevmoo/git.dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.0.0

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.0.0
  test_descriptor: ^1.0.3
